# Generated by Django 4.0 on 2021-12-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('consumer_id', models.AutoField(primary_key=True, serialize=False)),
                ('consumer_name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('postcode', models.IntegerField()),
                ('site', models.URLField(max_length=100)),
                ('transportation', models.CharField(choices=[('a', 'auto'), ('r', 'railway'), ('f', 'air')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=50)),
                ('molar_mass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('density', models.DecimalField(decimal_places=2, max_digits=4)),
                ('measure', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supplier_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='upload')),
                ('matrix_type', models.CharField(max_length=50)),
                ('ligand', models.CharField(max_length=50)),
                ('economic_stage', models.CharField(max_length=50)),
                ('registration', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('postcode', models.IntegerField()),
                ('site', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material_costs_1000units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_count', models.DecimalField(decimal_places=2, max_digits=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aac', models.IntegerField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consumer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immunology', models.BooleanField()),
                ('surgery', models.BooleanField()),
                ('allergology', models.BooleanField()),
                ('infectology', models.BooleanField()),
                ('intensive_therapy', models.BooleanField()),
                ('cardiology', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
