# Generated by Django 4.0 on 2021-12-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_economic_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='supplier_name',
        ),
        migrations.AlterField(
            model_name='material',
            name='measure',
            field=models.CharField(default='г', max_length=10),
        ),
    ]
