# Generated by Django 4.0 on 2021-12-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_material_supplier_name_alter_material_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='molar_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
