# Generated by Django 4.0 on 2021-12-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_consumer_postcode_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='app/img/not_avalaible.png', upload_to='upload'),
        ),
    ]
