# Generated by Django 4.0 on 2021-12-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='app/img/not_avalaible.png', upload_to='upload'),
        ),
    ]
